from google.cloud import bigquery
import pandas as pd


class BigQueryClient:
    """
    Handles BigQuery read and write operations
    for the Finance UUID IBAN enrichment pipeline.
    """

    def __init__(self):
        self.client = bigquery.Client()

    def get_finance_uuids(self):
        """
        Fetch distinct Finance UUIDs generated by dbt
        that require IBAN enrichment.
        """

        query = """
        SELECT finance_uuid
        FROM analytics_engineering_auto1.int_finance_uuid_queue
        """

        rows = self.client.query(query).result()

        return [row.finance_uuid for row in rows]

    def load_results(self, rows):

        table_id = (
            "analytics-engineering-464208."
            "analytics_engineering_auto1."
            "int_finance_uuid_iban"
        )
        #Convert API enrichment response into tabular format
        df = pd.DataFrame(rows)

        df["created_on"] = pd.to_datetime(
            df["created_on"],
            errors="coerce"
        )
        # Replace previous enrichment snapshot with latest API results
        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE
        )
        print(
                f"Truncating and loading {len(rows)} rows into {table_id}"
        )

        job = self.client.load_table_from_dataframe(
            df,
            table_id,
            job_config=job_config
        )

        job.result()

        print(
            f"Loaded {len(rows)} rows"
        )
